namespace unvell.ReoGrid.IO.OpenXML.Schema.Excel2009
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------


	// 
	// This source code was auto-generated by xsd, Version=4.6.1055.0.
	// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	//[System.Xml.Serialization.XmlRootAttribute("conditionalFormattings", Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main"/*, IsNullable = false*/)]
	public partial class CT_ConditionalFormattings
	{

		private CT_ConditionalFormatting[] conditionalFormattingField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("conditionalFormatting")]
		public CT_ConditionalFormatting[] conditionalFormatting
		{
			get { return this.conditionalFormattingField; }
			set { this.conditionalFormattingField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public class CT_ConditionalFormatting
	{

		private CT_CfRule[] cfRuleField;

		private CT_Sqref sqrefField;

		private CT_ExtensionList extLstField;

		private bool pivotField;

		public CT_ConditionalFormatting()
		{
			this.pivotField = false;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("cfRule")]
		public CT_CfRule[] cfRule
		{
			get { return this.cfRuleField; }
			set { this.cfRuleField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://schemas.microsoft.com/office/excel/2006/main")]
		public CT_Sqref sqref
		{
			get { return this.sqrefField; }
			set { this.sqrefField = value; }
		}

		/// <remarks/>
		public CT_ExtensionList extLst
		{
			get { return this.extLstField; }
			set { this.extLstField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool pivot
		{
			get { return this.pivotField; }
			set { this.pivotField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public partial class CT_CfRule
	{

		private string[] fField;

		private CT_ColorScale colorScaleField;

		private CT_DataBar dataBarField;

		private CT_IconSet iconSetField;

		private CT_Dxf dxfField;

		private CT_ExtensionList extLstField;

		private ST_CfType typeField;

		private bool typeFieldSpecified;

		private int priorityField;

		private bool priorityFieldSpecified;

		private bool stopIfTrueField;

		private bool aboveAverageField;

		private bool percentField;

		private bool bottomField;

		private ST_ConditionalFormattingOperator operatorField;

		private bool operatorFieldSpecified;

		private string textField;

		private ST_TimePeriod timePeriodField;

		private bool timePeriodFieldSpecified;

		private uint rankField;

		private bool rankFieldSpecified;

		private int stdDevField;

		private bool stdDevFieldSpecified;

		private bool equalAverageField;

		private bool activePresentField;

		private string idField;

		public CT_CfRule()
		{
			this.stopIfTrueField = false;
			this.aboveAverageField = true;
			this.percentField = false;
			this.bottomField = false;
			this.equalAverageField = false;
			this.activePresentField = false;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("f", Namespace = "http://schemas.microsoft.com/office/excel/2006/main")]
		public string[] f
		{
			get { return this.fField; }
			set { this.fField = value; }
		}

		/// <remarks/>
		public CT_ColorScale colorScale
		{
			get { return this.colorScaleField; }
			set { this.colorScaleField = value; }
		}

		/// <remarks/>
		public CT_DataBar dataBar
		{
			get { return this.dataBarField; }
			set { this.dataBarField = value; }
		}

		/// <remarks/>
		public CT_IconSet iconSet
		{
			get { return this.iconSetField; }
			set { this.iconSetField = value; }
		}

		/// <remarks/>
		public CT_Dxf dxf
		{
			get { return this.dxfField; }
			set { this.dxfField = value; }
		}

		/// <remarks/>
		public CT_ExtensionList extLst
		{
			get { return this.extLstField; }
			set { this.extLstField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ST_CfType type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool typeSpecified
		{
			get { return this.typeFieldSpecified; }
			set { this.typeFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int priority
		{
			get { return this.priorityField; }
			set { this.priorityField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool prioritySpecified
		{
			get { return this.priorityFieldSpecified; }
			set { this.priorityFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool stopIfTrue
		{
			get { return this.stopIfTrueField; }
			set { this.stopIfTrueField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool aboveAverage
		{
			get { return this.aboveAverageField; }
			set { this.aboveAverageField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool percent
		{
			get { return this.percentField; }
			set { this.percentField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool bottom
		{
			get { return this.bottomField; }
			set { this.bottomField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ST_ConditionalFormattingOperator @operator
		{
			get { return this.operatorField; }
			set { this.operatorField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool operatorSpecified
		{
			get { return this.operatorFieldSpecified; }
			set { this.operatorFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string text
		{
			get { return this.textField; }
			set { this.textField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ST_TimePeriod timePeriod
		{
			get { return this.timePeriodField; }
			set { this.timePeriodField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool timePeriodSpecified
		{
			get { return this.timePeriodFieldSpecified; }
			set { this.timePeriodFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public uint rank
		{
			get { return this.rankField; }
			set { this.rankField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool rankSpecified
		{
			get { return this.rankFieldSpecified; }
			set { this.rankFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int stdDev
		{
			get { return this.stdDevField; }
			set { this.stdDevField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool stdDevSpecified
		{
			get { return this.stdDevFieldSpecified; }
			set { this.stdDevFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool equalAverage
		{
			get { return this.equalAverageField; }
			set { this.equalAverageField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool activePresent
		{
			get { return this.activePresentField; }
			set { this.activePresentField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
		public string id
		{
			get { return this.idField; }
			set { this.idField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public partial class CT_ColorScale
	{

		private CT_Cfvo[] cfvoField;

		private CT_Color[] colorField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("cfvo")]
		public CT_Cfvo[] cfvo
		{
			get { return this.cfvoField; }
			set { this.cfvoField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("color")]
		public CT_Color[] color
		{
			get { return this.colorField; }
			set { this.colorField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public partial class CT_Cfvo
	{

		private string fField;

		private CT_ExtensionList extLstField;

		private ST_CfvoType typeField;

		private bool gteField;

		public CT_Cfvo()
		{
			this.gteField = true;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://schemas.microsoft.com/office/excel/2006/main")]
		public string f
		{
			get { return this.fField; }
			set { this.fField = value; }
		}

		/// <remarks/>
		public CT_ExtensionList extLst
		{
			get { return this.extLstField; }
			set { this.extLstField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ST_CfvoType type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool gte
		{
			get { return this.gteField; }
			set { this.gteField = value; }
		}
	}

	// /// <remarks/>
	// [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	// [System.SerializableAttribute()]
	// [System.Diagnostics.DebuggerStepThroughAttribute()]
	// [System.ComponentModel.DesignerCategoryAttribute("code")]
	// [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	// public partial class CT_ExtensionList
	// {
	// 
	//     private CT_Extension[] extField;
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlElementAttribute("ext")]
	//     public CT_Extension[] ext
	//     {
	//         get { return this.extField; }
	//         set { this.extField = value; }
	//     }
	// }

	// /// <remarks/>
	// [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	// [System.SerializableAttribute()]
	// [System.Diagnostics.DebuggerStepThroughAttribute()]
	// [System.ComponentModel.DesignerCategoryAttribute("code")]
	// [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	// public partial class CT_Extension
	// {
	// 
	//     private System.Xml.XmlElement anyField;
	// 
	//     private string uriField;
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlAnyElementAttribute()]
	//     public System.Xml.XmlElement Any
	//     {
	//         get { return this.anyField; }
	//         set { this.anyField = value; }
	//     }
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
	//     public string uri
	//     {
	//         get { return this.uriField; }
	//         set { this.uriField = value; }
	//     }
	// }

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/office/excel/2006/main")]
	[System.Xml.Serialization.XmlRootAttribute("sqref",
		 Namespace = "http://schemas.microsoft.com/office/excel/2006/main", IsNullable = false)]
	public partial class CT_Sqref
	{

		private bool editedField;

		private bool editedFieldSpecified;

		private bool splitField;

		private bool splitFieldSpecified;

		private bool adjustedField;

		private bool adjustedFieldSpecified;

		private bool adjustField;

		private bool adjustFieldSpecified;

		private string[] textField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool edited
		{
			get { return this.editedField; }
			set { this.editedField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool editedSpecified
		{
			get { return this.editedFieldSpecified; }
			set { this.editedFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool split
		{
			get { return this.splitField; }
			set { this.splitField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool splitSpecified
		{
			get { return this.splitFieldSpecified; }
			set { this.splitFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool adjusted
		{
			get { return this.adjustedField; }
			set { this.adjustedField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool adjustedSpecified
		{
			get { return this.adjustedFieldSpecified; }
			set { this.adjustedFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool adjust
		{
			get { return this.adjustField; }
			set { this.adjustField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool adjustSpecified
		{
			get { return this.adjustFieldSpecified; }
			set { this.adjustFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text
		{
			get { return this.textField; }
			set { this.textField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_CellProtection
	{

		private bool lockedField;

		private bool lockedFieldSpecified;

		private bool hiddenField;

		private bool hiddenFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public bool locked
		{
			get { return this.lockedField; }
			set { this.lockedField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool lockedSpecified
		{
			get { return this.lockedFieldSpecified; }
			set { this.lockedFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public bool hidden
		{
			get { return this.hiddenField; }
			set { this.hiddenField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool hiddenSpecified
		{
			get { return this.hiddenFieldSpecified; }
			set { this.hiddenFieldSpecified = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_BorderPr
	{

		private CT_Color colorField;

		private ST_BorderStyle styleField;

		public CT_BorderPr()
		{
			this.styleField = ST_BorderStyle.none;
		}

		/// <remarks/>
		public CT_Color color
		{
			get { return this.colorField; }
			set { this.colorField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(ST_BorderStyle.none)]
		public ST_BorderStyle style
		{
			get { return this.styleField; }
			set { this.styleField = value; }
		}
	}

	 // /// <remarks/>
	 // [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	 // [System.SerializableAttribute()]
	 // [System.Diagnostics.DebuggerStepThroughAttribute()]
	 // [System.ComponentModel.DesignerCategoryAttribute("code")]
	 // [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	 // public partial class CT_Color
	 // {
	 // 
	 //     private bool autoField;
	 // 
	 //     private bool autoFieldSpecified;
	 // 
	 //     private uint indexedField;
	 // 
	 //     private bool indexedFieldSpecified;
	 // 
	 //     private byte[] rgbField;
	 // 
	 //     private uint themeField;
	 // 
	 //     private bool themeFieldSpecified;
	 // 
	 //     private double tintField;
	 // 
	 //     public CT_Color()
	 //     {
	 //         this.tintField = 0D;
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
	 //     public bool auto
	 //     {
	 //         get { return this.autoField; }
	 //         set { this.autoField = value; }
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlIgnoreAttribute()]
	 //     public bool autoSpecified
	 //     {
	 //         get { return this.autoFieldSpecified; }
	 //         set { this.autoFieldSpecified = value; }
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
	 //     public uint indexed
	 //     {
	 //         get { return this.indexedField; }
	 //         set { this.indexedField = value; }
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlIgnoreAttribute()]
	 //     public bool indexedSpecified
	 //     {
	 //         get { return this.indexedFieldSpecified; }
	 //         set { this.indexedFieldSpecified = value; }
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
	 //          DataType = "hexBinary")]
	 //     public byte[] rgb
	 //     {
	 //         get { return this.rgbField; }
	 //         set { this.rgbField = value; }
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
	 //     public uint theme
	 //     {
	 //         get { return this.themeField; }
	 //         set { this.themeField = value; }
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlIgnoreAttribute()]
	 //     public bool themeSpecified
	 //     {
	 //         get { return this.themeFieldSpecified; }
	 //         set { this.themeFieldSpecified = value; }
	 //     }
	 // 
	 //     /// <remarks/>
	 //     [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
	 //     [System.ComponentModel.DefaultValueAttribute(0D)]
	 //     public double tint
	 //     {
	 //         get { return this.tintField; }
	 //         set { this.tintField = value; }
	 //     }
	 // }

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public enum ST_BorderStyle
	{

		/// <remarks/>
		none,

		/// <remarks/>
		thin,

		/// <remarks/>
		medium,

		/// <remarks/>
		dashed,

		/// <remarks/>
		dotted,

		/// <remarks/>
		thick,

		/// <remarks/>
		@double,

		/// <remarks/>
		hair,

		/// <remarks/>
		mediumDashed,

		/// <remarks/>
		dashDot,

		/// <remarks/>
		mediumDashDot,

		/// <remarks/>
		dashDotDot,

		/// <remarks/>
		mediumDashDotDot,

		/// <remarks/>
		slantDashDot,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_Border
	{

		private CT_BorderPr startField;

		private CT_BorderPr endField;

		private CT_BorderPr topField;

		private CT_BorderPr bottomField;

		private CT_BorderPr diagonalField;

		private CT_BorderPr verticalField;

		private CT_BorderPr horizontalField;

		private bool diagonalUpField;

		private bool diagonalUpFieldSpecified;

		private bool diagonalDownField;

		private bool diagonalDownFieldSpecified;

		private bool outlineField;

		public CT_Border()
		{
			this.outlineField = true;
		}

		/// <remarks/>
		public CT_BorderPr start
		{
			get { return this.startField; }
			set { this.startField = value; }
		}

		/// <remarks/>
		public CT_BorderPr end
		{
			get { return this.endField; }
			set { this.endField = value; }
		}

		/// <remarks/>
		public CT_BorderPr top
		{
			get { return this.topField; }
			set { this.topField = value; }
		}

		/// <remarks/>
		public CT_BorderPr bottom
		{
			get { return this.bottomField; }
			set { this.bottomField = value; }
		}

		/// <remarks/>
		public CT_BorderPr diagonal
		{
			get { return this.diagonalField; }
			set { this.diagonalField = value; }
		}

		/// <remarks/>
		public CT_BorderPr vertical
		{
			get { return this.verticalField; }
			set { this.verticalField = value; }
		}

		/// <remarks/>
		public CT_BorderPr horizontal
		{
			get { return this.horizontalField; }
			set { this.horizontalField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public bool diagonalUp
		{
			get { return this.diagonalUpField; }
			set { this.diagonalUpField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool diagonalUpSpecified
		{
			get { return this.diagonalUpFieldSpecified; }
			set { this.diagonalUpFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public bool diagonalDown
		{
			get { return this.diagonalDownField; }
			set { this.diagonalDownField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool diagonalDownSpecified
		{
			get { return this.diagonalDownFieldSpecified; }
			set { this.diagonalDownFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool outline
		{
			get { return this.outlineField; }
			set { this.outlineField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_CellAlignment
	{

		private ST_HorizontalAlignment horizontalField;

		private bool horizontalFieldSpecified;

		private ST_VerticalAlignment verticalField;

		private string textRotationField;

		private bool wrapTextField;

		private bool wrapTextFieldSpecified;

		private uint indentField;

		private bool indentFieldSpecified;

		private int relativeIndentField;

		private bool relativeIndentFieldSpecified;

		private bool justifyLastLineField;

		private bool justifyLastLineFieldSpecified;

		private bool shrinkToFitField;

		private bool shrinkToFitFieldSpecified;

		private uint readingOrderField;

		private bool readingOrderFieldSpecified;

		public CT_CellAlignment()
		{
			this.verticalField = ST_VerticalAlignment.bottom;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public ST_HorizontalAlignment horizontal
		{
			get { return this.horizontalField; }
			set { this.horizontalField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool horizontalSpecified
		{
			get { return this.horizontalFieldSpecified; }
			set { this.horizontalFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(ST_VerticalAlignment.bottom)]
		public ST_VerticalAlignment vertical
		{
			get { return this.verticalField; }
			set { this.verticalField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public string textRotation
		{
			get { return this.textRotationField; }
			set { this.textRotationField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public bool wrapText
		{
			get { return this.wrapTextField; }
			set { this.wrapTextField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool wrapTextSpecified
		{
			get { return this.wrapTextFieldSpecified; }
			set { this.wrapTextFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public uint indent
		{
			get { return this.indentField; }
			set { this.indentField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool indentSpecified
		{
			get { return this.indentFieldSpecified; }
			set { this.indentFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public int relativeIndent
		{
			get { return this.relativeIndentField; }
			set { this.relativeIndentField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool relativeIndentSpecified
		{
			get { return this.relativeIndentFieldSpecified; }
			set { this.relativeIndentFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public bool justifyLastLine
		{
			get { return this.justifyLastLineField; }
			set { this.justifyLastLineField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool justifyLastLineSpecified
		{
			get { return this.justifyLastLineFieldSpecified; }
			set { this.justifyLastLineFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public bool shrinkToFit
		{
			get { return this.shrinkToFitField; }
			set { this.shrinkToFitField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool shrinkToFitSpecified
		{
			get { return this.shrinkToFitFieldSpecified; }
			set { this.shrinkToFitFieldSpecified = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public uint readingOrder
		{
			get { return this.readingOrderField; }
			set { this.readingOrderField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool readingOrderSpecified
		{
			get { return this.readingOrderFieldSpecified; }
			set { this.readingOrderFieldSpecified = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public enum ST_HorizontalAlignment
	{

		/// <remarks/>
		general,

		/// <remarks/>
		left,

		/// <remarks/>
		center,

		/// <remarks/>
		right,

		/// <remarks/>
		fill,

		/// <remarks/>
		justify,

		/// <remarks/>
		centerContinuous,

		/// <remarks/>
		distributed,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public enum ST_VerticalAlignment
	{

		/// <remarks/>
		top,

		/// <remarks/>
		center,

		/// <remarks/>
		bottom,

		/// <remarks/>
		justify,

		/// <remarks/>
		distributed,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_GradientStop
	{

		private CT_Color colorField;

		private double positionField;

		/// <remarks/>
		public CT_Color color
		{
			get { return this.colorField; }
			set { this.colorField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public double position
		{
			get { return this.positionField; }
			set { this.positionField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_GradientFill
	{

		private CT_GradientStop[] stopField;

		private ST_GradientType typeField;

		private double degreeField;

		private double leftField;

		private double rightField;

		private double topField;

		private double bottomField;

		public CT_GradientFill()
		{
			this.typeField = ST_GradientType.linear;
			this.degreeField = 0D;
			this.leftField = 0D;
			this.rightField = 0D;
			this.topField = 0D;
			this.bottomField = 0D;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("stop")]
		public CT_GradientStop[] stop
		{
			get { return this.stopField; }
			set { this.stopField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(ST_GradientType.linear)]
		public ST_GradientType type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(0D)]
		public double degree
		{
			get { return this.degreeField; }
			set { this.degreeField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(0D)]
		public double left
		{
			get { return this.leftField; }
			set { this.leftField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(0D)]
		public double right
		{
			get { return this.rightField; }
			set { this.rightField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(0D)]
		public double top
		{
			get { return this.topField; }
			set { this.topField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(0D)]
		public double bottom
		{
			get { return this.bottomField; }
			set { this.bottomField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public enum ST_GradientType
	{

		/// <remarks/>
		linear,

		/// <remarks/>
		path,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_PatternFill
	{

		private CT_Color fgColorField;

		private CT_Color bgColorField;

		private ST_PatternType patternTypeField;

		private bool patternTypeFieldSpecified;

		/// <remarks/>
		public CT_Color fgColor
		{
			get { return this.fgColorField; }
			set { this.fgColorField = value; }
		}

		/// <remarks/>
		public CT_Color bgColor
		{
			get { return this.bgColorField; }
			set { this.bgColorField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public ST_PatternType patternType
		{
			get { return this.patternTypeField; }
			set { this.patternTypeField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool patternTypeSpecified
		{
			get { return this.patternTypeFieldSpecified; }
			set { this.patternTypeFieldSpecified = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public enum ST_PatternType
	{

		/// <remarks/>
		none,

		/// <remarks/>
		solid,

		/// <remarks/>
		mediumGray,

		/// <remarks/>
		darkGray,

		/// <remarks/>
		lightGray,

		/// <remarks/>
		darkHorizontal,

		/// <remarks/>
		darkVertical,

		/// <remarks/>
		darkDown,

		/// <remarks/>
		darkUp,

		/// <remarks/>
		darkGrid,

		/// <remarks/>
		darkTrellis,

		/// <remarks/>
		lightHorizontal,

		/// <remarks/>
		lightVertical,

		/// <remarks/>
		lightDown,

		/// <remarks/>
		lightUp,

		/// <remarks/>
		lightGrid,

		/// <remarks/>
		lightTrellis,

		/// <remarks/>
		gray125,

		/// <remarks/>
		gray0625,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public class CT_Fill
	{

		private object itemField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("gradientFill", typeof(CT_GradientFill))]
		[System.Xml.Serialization.XmlElementAttribute("patternFill", typeof(CT_PatternFill))]
		public object Item
		{
			get { return this.itemField; }
			set { this.itemField = value; }
		}

		[System.Xml.Serialization.XmlAnyElement]
		public System.Xml.XmlElement Any;
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_NumFmt
	{

		private uint numFmtIdField;

		private string formatCodeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public uint numFmtId
		{
			get { return this.numFmtIdField; }
			set { this.numFmtIdField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public string formatCode
		{
			get { return this.formatCodeField; }
			set { this.formatCodeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_Font
	{

		private object[] itemsField;

		private ItemsChoiceType[] itemsElementNameField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("b", typeof(CT_BooleanProperty))]
		[System.Xml.Serialization.XmlElementAttribute("charset", typeof(CT_IntProperty))]
		[System.Xml.Serialization.XmlElementAttribute("color", typeof(CT_Color))]
		[System.Xml.Serialization.XmlElementAttribute("condense", typeof(CT_BooleanProperty))]
		[System.Xml.Serialization.XmlElementAttribute("extend", typeof(CT_BooleanProperty))]
		[System.Xml.Serialization.XmlElementAttribute("family", typeof(CT_FontFamily))]
		[System.Xml.Serialization.XmlElementAttribute("i", typeof(CT_BooleanProperty))]
		[System.Xml.Serialization.XmlElementAttribute("name", typeof(CT_FontName))]
		[System.Xml.Serialization.XmlElementAttribute("outline", typeof(CT_BooleanProperty))]
		[System.Xml.Serialization.XmlElementAttribute("scheme", typeof(CT_FontScheme))]
		[System.Xml.Serialization.XmlElementAttribute("shadow", typeof(CT_BooleanProperty))]
		[System.Xml.Serialization.XmlElementAttribute("strike", typeof(CT_BooleanProperty))]
		[System.Xml.Serialization.XmlElementAttribute("sz", typeof(CT_FontSize))]
		[System.Xml.Serialization.XmlElementAttribute("u", typeof(CT_UnderlineProperty))]
		[System.Xml.Serialization.XmlElementAttribute("vertAlign", typeof(CT_VerticalAlignFontProperty))]
		[System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public ItemsChoiceType[] ItemsElementName
		{
			get { return this.itemsElementNameField; }
			set { this.itemsElementNameField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_BooleanProperty
	{

		private bool valField;

		public CT_BooleanProperty()
		{
			this.valField = true;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_IntProperty
	{

		private int valField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public int val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_FontFamily
	{

		private string valField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
			 DataType = "integer")]
		public string val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_FontName
	{

		private string valField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public string val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_FontScheme
	{

		private ST_FontScheme valField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public ST_FontScheme val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public enum ST_FontScheme
	{

		/// <remarks/>
		none,

		/// <remarks/>
		major,

		/// <remarks/>
		minor,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_FontSize
	{

		private double valField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public double val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_UnderlineProperty
	{

		private ST_UnderlineValues valField;

		public CT_UnderlineProperty()
		{
			this.valField = ST_UnderlineValues.single;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		[System.ComponentModel.DefaultValueAttribute(ST_UnderlineValues.single)]
		public ST_UnderlineValues val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public enum ST_UnderlineValues
	{

		/// <remarks/>
		single,

		/// <remarks/>
		@double,

		/// <remarks/>
		singleAccounting,

		/// <remarks/>
		doubleAccounting,

		/// <remarks/>
		none,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	public partial class CT_VerticalAlignFontProperty
	{

		private ST_VerticalAlignRun valField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public ST_VerticalAlignRun val
		{
			get { return this.valField; }
			set { this.valField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purl.oclc.org/ooxml/officeDocument/sharedTypes")]
	public enum ST_VerticalAlignRun
	{

		/// <remarks/>
		baseline,

		/// <remarks/>
		superscript,

		/// <remarks/>
		subscript,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
		 IncludeInSchema = false)]
	public enum ItemsChoiceType
	{

		/// <remarks/>
		b,

		/// <remarks/>
		charset,

		/// <remarks/>
		color,

		/// <remarks/>
		condense,

		/// <remarks/>
		extend,

		/// <remarks/>
		family,

		/// <remarks/>
		i,

		/// <remarks/>
		name,

		/// <remarks/>
		outline,

		/// <remarks/>
		scheme,

		/// <remarks/>
		shadow,

		/// <remarks/>
		strike,

		/// <remarks/>
		sz,

		/// <remarks/>
		u,

		/// <remarks/>
		vertAlign,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", TypeName = "dxf")]
	public class CT_Dxf
	{

		private CT_Font fontField;

		private CT_NumFmt numFmtField;

		private CT_Fill fillField;

		private CT_CellAlignment alignmentField;

		private CT_Border borderField;

		private CT_CellProtection protectionField;

		private CT_ExtensionList extLstField;

		[System.Xml.Serialization.XmlElement(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
		public CT_Font font
		{
			get { return this.fontField; }
			set { this.fontField = value; }
		}

		[System.Xml.Serialization.XmlElement(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
		public CT_NumFmt numFmt
		{
			get { return this.numFmtField; }
			set { this.numFmtField = value; }
		}

		[System.Xml.Serialization.XmlElement(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
		public CT_Fill fill
		{
			get { return this.fillField; }
			set { this.fillField = value; }
		}

		
		[System.Xml.Serialization.XmlElement(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
		public CT_CellAlignment alignment
		{
			get { return this.alignmentField; }
			set { this.alignmentField = value; }
		}

		[System.Xml.Serialization.XmlElement(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
		public CT_Border border
		{
			get { return this.borderField; }
			set { this.borderField = value; }
		}

		[System.Xml.Serialization.XmlElement(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
		public CT_CellProtection protection
		{
			get { return this.protectionField; }
			set { this.protectionField = value; }
		}

		[System.Xml.Serialization.XmlElement(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
		public CT_ExtensionList extLst
		{
			get { return this.extLstField; }
			set { this.extLstField = value; }
		}

		// [System.Xml.Serialization.XmlAnyElement]
		// public System.Xml.XmlElement Any;
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public partial class CT_CfIcon
	{

		private ST_IconSetType iconSetField;

		private uint iconIdField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ST_IconSetType iconSet
		{
			get { return this.iconSetField; }
			set { this.iconSetField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public uint iconId
		{
			get { return this.iconIdField; }
			set { this.iconIdField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public enum ST_IconSetType
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3Arrows")] Item3Arrows,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3ArrowsGray")] Item3ArrowsGray,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3Flags")] Item3Flags,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3TrafficLights1")] Item3TrafficLights1,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3TrafficLights2")] Item3TrafficLights2,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3Signs")] Item3Signs,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3Symbols")] Item3Symbols,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3Symbols2")] Item3Symbols2,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("4Arrows")] Item4Arrows,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("4ArrowsGray")] Item4ArrowsGray,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("4RedToBlack")] Item4RedToBlack,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("4Rating")] Item4Rating,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("4TrafficLights")] Item4TrafficLights,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("5Arrows")] Item5Arrows,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("5ArrowsGray")] Item5ArrowsGray,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("5Rating")] Item5Rating,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("5Quarters")] Item5Quarters,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3Stars")] Item3Stars,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3Triangles")] Item3Triangles,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("5Boxes")] Item5Boxes,

		/// <remarks/>
		NoIcons,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public partial class CT_IconSet
	{

		private CT_Cfvo[] cfvoField;

		private CT_CfIcon[] cfIconField;

		private ST_IconSetType iconSetField;

		private bool showValueField;

		private bool percentField;

		private bool reverseField;

		private bool customField;

		public CT_IconSet()
		{
			this.iconSetField = ST_IconSetType.Item3TrafficLights1;
			this.showValueField = true;
			this.percentField = true;
			this.reverseField = false;
			this.customField = false;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("cfvo")]
		public CT_Cfvo[] cfvo
		{
			get { return this.cfvoField; }
			set { this.cfvoField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("cfIcon")]
		public CT_CfIcon[] cfIcon
		{
			get { return this.cfIconField; }
			set { this.cfIconField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(ST_IconSetType.Item3TrafficLights1)]
		public ST_IconSetType iconSet
		{
			get { return this.iconSetField; }
			set { this.iconSetField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool showValue
		{
			get { return this.showValueField; }
			set { this.showValueField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool percent
		{
			get { return this.percentField; }
			set { this.percentField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool reverse
		{
			get { return this.reverseField; }
			set { this.reverseField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool custom
		{
			get { return this.customField; }
			set { this.customField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public partial class CT_DataBar
	{

		private CT_Cfvo[] cfvoField;

		private CT_Color fillColorField;

		private CT_Color borderColorField;

		private CT_Color negativeFillColorField;

		private CT_Color negativeBorderColorField;

		private CT_Color axisColorField;

		private uint minLengthField;

		private uint maxLengthField;

		private bool showValueField;

		private bool borderField;

		private bool gradientField;

		private ST_DataBarDirection directionField;

		private bool negativeBarColorSameAsPositiveField;

		private bool negativeBarBorderColorSameAsPositiveField;

		private ST_DataBarAxisPosition axisPositionField;

		public CT_DataBar()
		{
			this.minLengthField = ((uint) (10));
			this.maxLengthField = ((uint) (90));
			this.showValueField = true;
			this.borderField = false;
			this.gradientField = true;
			this.directionField = ST_DataBarDirection.context;
			this.negativeBarColorSameAsPositiveField = false;
			this.negativeBarBorderColorSameAsPositiveField = true;
			this.axisPositionField = ST_DataBarAxisPosition.automatic;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("cfvo")]
		public CT_Cfvo[] cfvo
		{
			get { return this.cfvoField; }
			set { this.cfvoField = value; }
		}

		/// <remarks/>
		public CT_Color fillColor
		{
			get { return this.fillColorField; }
			set { this.fillColorField = value; }
		}

		/// <remarks/>
		public CT_Color borderColor
		{
			get { return this.borderColorField; }
			set { this.borderColorField = value; }
		}

		/// <remarks/>
		public CT_Color negativeFillColor
		{
			get { return this.negativeFillColorField; }
			set { this.negativeFillColorField = value; }
		}

		/// <remarks/>
		public CT_Color negativeBorderColor
		{
			get { return this.negativeBorderColorField; }
			set { this.negativeBorderColorField = value; }
		}

		/// <remarks/>
		public CT_Color axisColor
		{
			get { return this.axisColorField; }
			set { this.axisColorField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(typeof(uint), "10")]
		public uint minLength
		{
			get { return this.minLengthField; }
			set { this.minLengthField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(typeof(uint), "90")]
		public uint maxLength
		{
			get { return this.maxLengthField; }
			set { this.maxLengthField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool showValue
		{
			get { return this.showValueField; }
			set { this.showValueField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool border
		{
			get { return this.borderField; }
			set { this.borderField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool gradient
		{
			get { return this.gradientField; }
			set { this.gradientField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(ST_DataBarDirection.context)]
		public ST_DataBarDirection direction
		{
			get { return this.directionField; }
			set { this.directionField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool negativeBarColorSameAsPositive
		{
			get { return this.negativeBarColorSameAsPositiveField; }
			set { this.negativeBarColorSameAsPositiveField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool negativeBarBorderColorSameAsPositive
		{
			get { return this.negativeBarBorderColorSameAsPositiveField; }
			set { this.negativeBarBorderColorSameAsPositiveField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(ST_DataBarAxisPosition.automatic)]
		public ST_DataBarAxisPosition axisPosition
		{
			get { return this.axisPositionField; }
			set { this.axisPositionField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public enum ST_DataBarDirection
	{

		/// <remarks/>
		context,

		/// <remarks/>
		leftToRight,

		/// <remarks/>
		rightToLeft,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public enum ST_DataBarAxisPosition
	{

		/// <remarks/>
		automatic,

		/// <remarks/>
		middle,

		/// <remarks/>
		none,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(
		 Namespace = "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main")]
	public enum ST_CfvoType
	{

		/// <remarks/>
		num,

		/// <remarks/>
		percent,

		/// <remarks/>
		max,

		/// <remarks/>
		min,

		/// <remarks/>
		formula,

		/// <remarks/>
		percentile,

		/// <remarks/>
		autoMin,

		/// <remarks/>
		autoMax,
	}

	// /// <remarks/>
	// [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	// [System.SerializableAttribute()]
	// [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	// public enum ST_CfType
	// {
	// 
	//     /// <remarks/>
	//     expression,
	// 
	//     /// <remarks/>
	//     cellIs,
	// 
	//     /// <remarks/>
	//     colorScale,
	// 
	//     /// <remarks/>
	//     dataBar,
	// 
	//     /// <remarks/>
	//     iconSet,
	// 
	//     /// <remarks/>
	//     top10,
	// 
	//     /// <remarks/>
	//     uniqueValues,
	// 
	//     /// <remarks/>
	//     duplicateValues,
	// 
	//     /// <remarks/>
	//     containsText,
	// 
	//     /// <remarks/>
	//     notContainsText,
	// 
	//     /// <remarks/>
	//     beginsWith,
	// 
	//     /// <remarks/>
	//     endsWith,
	// 
	//     /// <remarks/>
	//     containsBlanks,
	// 
	//     /// <remarks/>
	//     notContainsBlanks,
	// 
	//     /// <remarks/>
	//     containsErrors,
	// 
	//     /// <remarks/>
	//     notContainsErrors,
	// 
	//     /// <remarks/>
	//     timePeriod,
	// 
	//     /// <remarks/>
	//     aboveAverage,
	// }

	// /// <remarks/>
	// [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	// [System.SerializableAttribute()]
	// [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	// public enum ST_ConditionalFormattingOperator
	// {
	// 
	//     /// <remarks/>
	//     lessThan,
	// 
	//     /// <remarks/>
	//     lessThanOrEqual,
	// 
	//     /// <remarks/>
	//     equal,
	// 
	//     /// <remarks/>
	//     notEqual,
	// 
	//     /// <remarks/>
	//     greaterThanOrEqual,
	// 
	//     /// <remarks/>
	//     greaterThan,
	// 
	//     /// <remarks/>
	//     between,
	// 
	//     /// <remarks/>
	//     notBetween,
	// 
	//     /// <remarks/>
	//     containsText,
	// 
	//     /// <remarks/>
	//     notContains,
	// 
	//     /// <remarks/>
	//     beginsWith,
	// 
	//     /// <remarks/>
	//     endsWith,
	// }

	// /// <remarks/>
	// [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	// [System.SerializableAttribute()]
	// [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
	// public enum ST_TimePeriod
	// {
	// 
	//     /// <remarks/>
	//     today,
	// 
	//     /// <remarks/>
	//     yesterday,
	// 
	//     /// <remarks/>
	//     tomorrow,
	// 
	//     /// <remarks/>
	//     last7Days,
	// 
	//     /// <remarks/>
	//     thisMonth,
	// 
	//     /// <remarks/>
	//     lastMonth,
	// 
	//     /// <remarks/>
	//     nextMonth,
	// 
	//     /// <remarks/>
	//     thisWeek,
	// 
	//     /// <remarks/>
	//     lastWeek,
	// 
	//     /// <remarks/>
	//     nextWeek,
	// }

	// /// <remarks/>
	// [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	// [System.SerializableAttribute()]
	// [System.Diagnostics.DebuggerStepThroughAttribute()]
	// [System.ComponentModel.DesignerCategoryAttribute("code")]
	// [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/office/excel/2006/main")]
	// [System.Xml.Serialization.XmlRootAttribute("ref", Namespace = "http://schemas.microsoft.com/office/excel/2006/main",
	//      IsNullable = false)]
	// public partial class CT_Ref
	// {
	// 
	//     private bool editedField;
	// 
	//     private bool editedFieldSpecified;
	// 
	//     private bool adjustedField;
	// 
	//     private bool adjustedFieldSpecified;
	// 
	//     private bool adjustField;
	// 
	//     private bool adjustFieldSpecified;
	// 
	//     private string valueField;
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlAttributeAttribute()]
	//     public bool edited
	//     {
	//         get { return this.editedField; }
	//         set { this.editedField = value; }
	//     }
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlIgnoreAttribute()]
	//     public bool editedSpecified
	//     {
	//         get { return this.editedFieldSpecified; }
	//         set { this.editedFieldSpecified = value; }
	//     }
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlAttributeAttribute()]
	//     public bool adjusted
	//     {
	//         get { return this.adjustedField; }
	//         set { this.adjustedField = value; }
	//     }
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlIgnoreAttribute()]
	//     public bool adjustedSpecified
	//     {
	//         get { return this.adjustedFieldSpecified; }
	//         set { this.adjustedFieldSpecified = value; }
	//     }
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlAttributeAttribute()]
	//     public bool adjust
	//     {
	//         get { return this.adjustField; }
	//         set { this.adjustField = value; }
	//     }
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlIgnoreAttribute()]
	//     public bool adjustSpecified
	//     {
	//         get { return this.adjustFieldSpecified; }
	//         set { this.adjustFieldSpecified = value; }
	//     }
	// 
	//     /// <remarks/>
	//     [System.Xml.Serialization.XmlTextAttribute()]
	//     public string Value
	//     {
	//         get { return this.valueField; }
	//         set { this.valueField = value; }
	//     }
	// }
}