namespace unvell.ReoGrid.IO.OpenXML.Schema
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------


    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    // [System.SerializableAttribute()]
    // [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    // [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    // [System.Xml.Serialization.XmlRootAttribute("ConditionalFormatting", Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main", IsNullable = false)]
    public partial class CT_ConditionalFormatting
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cfRule")]
        public CT_CfRule[] cfRule;

        /// <remarks/>
        public CT_ExtensionList extLst;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool pivot;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.Xml.Serialization.XmlAttribute()]
        public string[] sqref { get; set; }

        public CT_ConditionalFormatting()
        {
            this.pivot = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_CfRule
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("formula")] public string[] formula;

        /// <remarks/>
        public CT_ColorScale colorScale;

        /// <remarks/>
        public CT_DataBar dataBar;

        /// <remarks/>
        public CT_IconSet iconSet;

        /// <remarks/>
        public CT_ExtensionList extLst;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public
            ST_CfType type;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool typeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public uint
            dxfId;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool dxfIdSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public int
            priority;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(false)] public bool stopIfTrue;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(true)] public bool aboveAverage;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(false)] public bool percent;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(false)] public bool bottom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public
            ST_ConditionalFormattingOperator @operator;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool operatorSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public string
            text;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public
            ST_TimePeriod timePeriod;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool timePeriodSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public uint
            rank;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool rankSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public int
            stdDev;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool stdDevSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(false)] public bool equalAverage;

        public CT_CfRule()
        {
            this.stopIfTrue = false;
            this.aboveAverage = true;
            this.percent = false;
            this.bottom = false;
            this.equalAverage = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_ColorScale
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cfvo")] public CT_Cfvo[] cfvo;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("color")] public CT_Color[] color;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_Cfvo
    {

        /// <remarks/>
        public CT_ExtensionList extLst;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public
            ST_CfvoType type;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public string
            val;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(true)] public bool gte;

        public CT_Cfvo()
        {
            this.gte = true;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_ExtensionList
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ext")] public CT_Extension[] ext;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_Extension
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()] public System.Xml.XmlElement Any;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified,*/
             DataType = "token")] public string uri;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_IconSet
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cfvo")] public CT_Cfvo[] cfvo;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(ST_IconSetType.Item3TrafficLights1)] public ST_IconSetType iconSet;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(true)] public bool showValue;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(true)] public bool percent;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(false)] public bool reverse;

        public CT_IconSet()
        {
            this.iconSet = ST_IconSetType.Item3TrafficLights1;
            this.showValue = true;
            this.percent = true;
            this.reverse = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public enum ST_IconSetType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3Arrows")] Item3Arrows,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3ArrowsGray")] Item3ArrowsGray,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3Flags")] Item3Flags,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3TrafficLights1")] Item3TrafficLights1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3TrafficLights2")] Item3TrafficLights2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3Signs")] Item3Signs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3Symbols")] Item3Symbols,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3Symbols2")] Item3Symbols2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4Arrows")] Item4Arrows,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4ArrowsGray")] Item4ArrowsGray,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4RedToBlack")] Item4RedToBlack,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4Rating")] Item4Rating,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4TrafficLights")] Item4TrafficLights,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5Arrows")] Item5Arrows,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5ArrowsGray")] Item5ArrowsGray,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5Rating")] Item5Rating,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5Quarters")] Item5Quarters,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_DataBar
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cfvo")] public CT_Cfvo[] cfvo;

        /// <remarks/>
        public CT_Color color;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(typeof(uint), "10")] public uint minLength;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(typeof(uint), "90")] public uint maxLength;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(true)] public bool showValue;

        public CT_DataBar()
        {
            this.minLength = ((uint) (10));
            this.maxLength = ((uint) (90));
            this.showValue = true;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public partial class CT_Color
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public bool
            auto;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool autoSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public uint
            indexed;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool indexedSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified,*/
             DataType = "hexBinary")] public byte[] rgb;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] public uint
            theme;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()] public bool themeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(/*Form = System.Xml.Schema.XmlSchemaForm.Qualified*/)] [System.ComponentModel.DefaultValueAttribute(0D)] public double tint;

        public CT_Color()
        {
            this.tint = 0D;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public enum ST_CfvoType
    {

        /// <remarks/>
        num,

        /// <remarks/>
        percent,

        /// <remarks/>
        max,

        /// <remarks/>
        min,

        /// <remarks/>
        formula,

        /// <remarks/>
        percentile,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public enum ST_CfType
    {

        /// <remarks/>
        expression,

        /// <remarks/>
        cellIs,

        /// <remarks/>
        colorScale,

        /// <remarks/>
        dataBar,

        /// <remarks/>
        iconSet,

        /// <remarks/>
        top10,

        /// <remarks/>
        uniqueValues,

        /// <remarks/>
        duplicateValues,

        /// <remarks/>
        containsText,

        /// <remarks/>
        notContainsText,

        /// <remarks/>
        beginsWith,

        /// <remarks/>
        endsWith,

        /// <remarks/>
        containsBlanks,

        /// <remarks/>
        notContainsBlanks,

        /// <remarks/>
        containsErrors,

        /// <remarks/>
        notContainsErrors,

        /// <remarks/>
        timePeriod,

        /// <remarks/>
        aboveAverage,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public enum ST_ConditionalFormattingOperator
    {

        /// <remarks/>
        lessThan,

        /// <remarks/>
        lessThanOrEqual,

        /// <remarks/>
        equal,

        /// <remarks/>
        notEqual,

        /// <remarks/>
        greaterThanOrEqual,

        /// <remarks/>
        greaterThan,

        /// <remarks/>
        between,

        /// <remarks/>
        notBetween,

        /// <remarks/>
        containsText,

        /// <remarks/>
        notContains,

        /// <remarks/>
        beginsWith,

        /// <remarks/>
        endsWith,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/spreadsheetml/2006/main")]
    public enum ST_TimePeriod
    {

        /// <remarks/>
        today,

        /// <remarks/>
        yesterday,

        /// <remarks/>
        tomorrow,

        /// <remarks/>
        last7Days,

        /// <remarks/>
        thisMonth,

        /// <remarks/>
        lastMonth,

        /// <remarks/>
        nextMonth,

        /// <remarks/>
        thisWeek,

        /// <remarks/>
        lastWeek,

        /// <remarks/>
        nextWeek,
    }
}